### ISSUE TITLE
Unable to ng build -prod with angular 2 cli

### ISSUE THREAD

**Issue by arsenybobrov** [cedvdb/ng2draggable#10]
I am using angular cli:
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7
node: 6.9.5

I am unable to build prod (ng build -prod), because of the error:
ERROR in Unexpected value 'Draggable in C:/.../node_modules/ng2draggable/draggable.directive.d.ts' declared by the module 'AppModule in C:/...r/src/app/app.module.ts'

Thank you for a feedback.

**Comment by cedvdb** [comment]
@arsenybobrov Could you share your project ?

**Comment by paritosh149** [comment]
Thanks for this very helpful component.
However, I tried to include this component in my Angular2+Typescript2 project and encountered following error:

tsc -p ./

node_modules/ng2draggable/draggable.directive.ts(88,7): error TS7032: Property 'ng2DraggableHandle' implicitly has type 'any', because its set accessor lacks a para
meter type annotation.
node_modules/ng2draggable/draggable.directive.ts(88,26): error TS7006: Parameter 'handle' implicitly has an 'any' type.

Please share any insight how to remove this error.

**Comment by cedvdb** [comment]
@paritosh149 can you tell me if you still have the error, because I don't have any ? Reinstall the new version

**Comment by arsenybobrov** [comment]
Hi @cedvdb unfortunately my project is not public. My team has deployed the project on different machines and on some we had this error and on some not. I suppose some kind of dependency conflicts, although we do not know which exactly... machine setup is equal...

Anyway, thank you for this plugin!
