### ISSUE TITLE
In which version was it tested?

### ISSUE THREAD

**Issue by sreejithpune** [cedvdb/ng2draggable#11]
npm version ?
tsc version ?
node version ?

**Comment by cedvdb** [comment]
typescript version used in the demo is  `"typescript": "~2.0.0"`,
The node version I'm currently using is:
npm I have `4.1.2`
node `7.6`

The master branch is now the demo app. You can clone it and check it out.
I because someone had an error yesterday with typescript. You might wanna update and see if it resolve your issue (if you have any)
