### ISSUE TITLE
Not working on small images or Ipad

### ISSUE THREAD

**Issue by stex2727** [cedvdb/ng2draggable#4]
Hi, couple of niggly things, for some reason this code seems to stop dragging when there is a very small image and the mouse is moved rapidly.  It is also not working on the IPad.

Thanks for the code though, helped me understand the events/directive a little better.

**Comment by cedvdb** [comment]
@stex2727  sorry for the late reply.

I changed the code, such that the event mousemove is captured on the document instead of the element. So it should work now for small images.

For the ipad thing feel free to make a pull request if you want to change things. I've no ipad and I don't really have time right now to check it out, or maybe I'm being lazy.
